import { AppState, Language } from './types';

export const PERMISSIONS_LIST = [
  { id: 'view_vault', label: 'View Vault Balance', category: 'Vault' },
  { id: 'view_projects', label: 'View All Projects', category: 'Projects' },
  { id: 'view_my_projects', label: 'View My Projects Only', category: 'Projects' },
  { id: 'create_project', label: 'Create Projects', category: 'Projects' },
  { id: 'manage_project_funds', label: 'Fund/Withdraw Projects', category: 'Projects' },
  { id: 'view_spending', label: 'View Spending', category: 'Spending' },
  { id: 'log_expense', label: 'Log Expenses', category: 'Spending' },
  { id: 'view_activity', label: 'View All Activity', category: 'Activity' },
  { id: 'view_my_activity', label: 'View My Activity Only', category: 'Activity' },
  { id: 'view_accounts', label: 'View Accounts', category: 'Accounts' },
  { id: 'add_money', label: 'Add Money to Vault', category: 'Accounts' },
  { id: 'give_money', label: 'Give Money to User', category: 'Accounts' },
  { id: 'view_reports', label: 'View Reports', category: 'Reports' },
  { id: 'access_admin', label: 'Access Admin Panel', category: 'Admin' },
];

// Helper to get all permissions for Admin
const ALL_PERMISSIONS = PERMISSIONS_LIST.map(p => p.id);

export const DEFAULT_STATE: AppState = {
  vaultBalance: 0,
  projects: [],
  spending: [],
  activityLog: [],
  users: [
    { 
      id: 1, 
      username: 'admin', 
      password: '1', 
      role: 'Admin', 
      fullName: 'System Admin',
      permissions: ALL_PERMISSIONS,
      isVisibleToManagers: false
    },
    { 
      id: 2, 
      username: 'manager', 
      password: '1', 
      role: 'Manager', 
      fullName: 'Manager User',
      permissions: [
        'view_vault', 'view_projects', 'create_project', 'manage_project_funds',
        'view_spending', 'log_expense', 'view_activity', 'view_accounts',
        'add_money', 'give_money', 'view_reports'
      ]
    },
    { 
      id: 3, 
      username: 'emp', 
      password: '1', 
      role: 'Employee', 
      fullName: 'Employee User',
      permissions: ['view_my_projects', 'view_my_activity']
    },
  ],
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    welcome_back: "Welcome Back", username_placeholder: "Username", password_placeholder: "Password", login: "Login", logout: "Logout",
    vault_balance: "Vault Balance", vault_details: "Vault Details", projects: "Projects", my_projects: "My Projects",
    active: "Active", spent: "Spent", completed: "Completed", spending: "Spending", start_date: "Start Date", end_date: "End Date",
    filter: "Filter", activity_log: "Activity Log", my_activity: "My Activity", member_accounts: "Member Accounts",
    accounting_reports: "Accounting & Reports", admin_panel: "Admin Panel", manage_users: "Manage Users",
    add_employee: "Add Employee", export_data: "Export Data", import_data: "Import Data",
    add_money: "Add Money", withdraw: "Withdraw", fund: "Fund", create_project: "Create Project", log_expense: "Log Expense",
    give_money: "Give Money", description: "Description", amount: "Amount", note: "Note (Optional)",
    save_changes: "Save Changes", delete: "Delete", edit: "Edit", confirm: "Confirm", cancel: "Cancel",
    total_income: "Total Income", total_expenses: "Total Expenses", net_profit: "Net Profit",
    house: "House", general: "General", project: "Project", users: "Users",
    type: "Type", tag: "Tag", search: "Search...",
    dashboard: "Dashboard", insufficient_funds: "Insufficient Funds in Vault",
    permissions: "Permissions", edit_user: "Edit User", create_user: "Create User",
    
    // New Translations
    liquid_cash: "Liquid Cash (Vault)", total_assets: "Total Assets", allocated_funds: "Allocated Funds",
    locked_in: "Locked in", asset_allocation: "Asset Allocation", active_projects_breakdown: "Active Projects Breakdown",
    no_active_projects: "No active projects currently.", access_denied: "Access Denied",
    goal: "Goal", current_balance: "Current Balance", reactivate: "Reactivate", funded: "Funded",
    project_activity: "Project Activity", no_activity: "No activity yet", remaining_goal_space: "Remaining goal space",
    confirm_completion: "Confirm Completion", confirm_completion_text: "Are you sure you want to spend the remaining balance of",
    and_close_project: "and close this project?", yes_complete: "Yes, Complete",
    confirm_reactivation: "Confirm Reactivation", confirm_reactivation_text: "Are you sure you want to reactivate this project?",
    restore_funds_note: "The spent money will be restored to the project balance.", yes_reactivate: "Yes, Reactivate",
    edit_project: "Edit Project", project_name: "Project Name", funding_goal: "Funding Goal",
    security_check: "Security Check", delete_project_title: "Delete Project?",
    delete_project_text: "Funds will be returned to the Vault. Type code to confirm.",
    enter_security_code: "Enter Security Code", type_code: "Type the 3-digit code",
    delete_project_btn: "Delete Project", no_projects_found: "No projects found in this category.",
    all: "All", user: "User", no_records: "No records found.",
    general_view: "General", personal_view: "Personal", editing: "Editing",
    warning_edit: "Warning: Changing the amount will adjust the Vault balance.",
    confirm_deletion_title: "Confirm Deletion", confirm_deletion_text: "To delete this activity, type the code below.",
    delete_log: "Delete Log", visible_to_managers: "Visible to Managers",
    hidden_from_managers: "Hidden from Managers", account_activity: "Account Activity",
    operational_actions: "Operational Actions", recent_history: "Recent History",
    my_account_activity: "My Account Activity", actions_performed: "Actions Performed",
    no_records_section: "No records found in this section.", log_details: "Log Details",
    click_to_hide: "Visible to Managers (Click to Hide)", click_to_show: "Hidden from Managers (Click to Show)",
    no_accounts: "No accounts found.", deposited_by: "Deposited By", recipient: "Recipient",
    expense_name: "Expense Name", select_user: "Select User",

    // Admin & Reports
    member: "Member (User)", all_members: "All Members", all_types: "All Types",
    income_type: "Income (Add Money)", spending_type: "Spending", fund_project_type: "Fund Project",
    withdraw_project_type: "Withdraw Project", transfer_type: "Transfers (Give)", export_pdf_btn: "Export PDF",
    user_header: "User", role_header: "Role", actions_header: "Actions", capabilities: "capabilities enabled",
    data_mgmt: "Data Management", role_label_display: "Role (Display Only)",
    visible_desc: "If checked, Managers can see this account in reports and lists.",
    filter_by_tag: "Filter by Tag..."
  },
  ar: {
    welcome_back: "مرحباً بعودتك", username_placeholder: "اسم المستخدم", password_placeholder: "كلمة المرور", login: "تسجيل الدخول", logout: "تسجيل الخروج",
    vault_balance: "رصيد الخزنة", vault_details: "تفاصيل الخزنة", projects: "المشاريع", my_projects: "مشاريعي",
    active: "نشطة", spent: "منفقة", completed: "مكتملة", spending: "المصاريف", start_date: "تاريخ البدء", end_date: "تاريخ الانتهاء",
    filter: "تصفية", activity_log: "سجل النشاطات", my_activity: "نشاطاتي", member_accounts: "حسابات الأعضاء",
    accounting_reports: "المحاسبة والتقارير", admin_panel: "لوحة التحكم", manage_users: "إدارة المستخدمين",
    add_employee: "إضافة موظف", export_data: "تصدير البيانات", import_data: "استيراد البيانات",
    add_money: "إضافة مال", withdraw: "سحب", fund: "تمويل", create_project: "إنشاء مشروع", log_expense: "تسجيل مصروف",
    give_money: "إعطاء مال", description: "الوصف", amount: "المبلغ", note: "ملاحظة (اختياري)",
    save_changes: "حفظ التغييرات", delete: "حذف", edit: "تعديل", confirm: "تأكيد", cancel: "إلغاء",
    total_income: "إجمالي الدخل", total_expenses: "إجمالي المصاريف", net_profit: "صافي الربح",
    house: "المنزل", general: "عام", project: "مشروع", users: "مستخدمين",
    type: "النوع", tag: "وسم", search: "بحث...",
    dashboard: "لوحة القيادة", insufficient_funds: "رصيد غير كافي في الخزنة",
    permissions: "الأذونات", edit_user: "تعديل المستخدم", create_user: "إنشاء مستخدم",

    // New Translations AR
    liquid_cash: "السيولة النقدية (الخزنة)", total_assets: "إجمالي الأصول", allocated_funds: "الأموال المخصصة",
    locked_in: "محتجزة في", asset_allocation: "توزيع الأصول", active_projects_breakdown: "تفاصيل المشاريع النشطة",
    no_active_projects: "لا توجد مشاريع نشطة حالياً.", access_denied: "تم رفض الوصول",
    goal: "الهدف", current_balance: "الرصيد الحالي", reactivate: "إعادة تفعيل", funded: "تم التمويل",
    project_activity: "نشاط المشروع", no_activity: "لا يوجد نشاط بعد", remaining_goal_space: "المبلغ المتبقي للهدف",
    confirm_completion: "تأكيد الإكمال", confirm_completion_text: "هل أنت متأكد أنك تريد صرف الرصيد المتبقي البالغ",
    and_close_project: "وإغلاق هذا المشروع؟", yes_complete: "نعم، إكمال",
    confirm_reactivation: "تأكيد إعادة التفعيل", confirm_reactivation_text: "هل أنت متأكد أنك تريد إعادة تفعيل هذا المشروع؟",
    restore_funds_note: "سيتم استعادة الأموال المصروفة إلى رصيد المشروع.", yes_reactivate: "نعم، إعادة تفعيل",
    edit_project: "تعديل المشروع", project_name: "اسم المشروع", funding_goal: "الهدف المالي",
    security_check: "التحقق الأمني", delete_project_title: "حذف المشروع؟",
    delete_project_text: "سيتم إعادة الأموال إلى الخزنة. اكتب الرمز للتأكيد.",
    enter_security_code: "أدخل رمز الأمان", type_code: "اكتب الرمز المكون من 3 أرقام",
    delete_project_btn: "حذف المشروع", no_projects_found: "لا توجد مشاريع في هذه الفئة.",
    all: "الكل", user: "مستخدم", no_records: "لا توجد سجلات.",
    general_view: "عام", personal_view: "شخصي", editing: "جاري التعديل",
    warning_edit: "تحذير: تغيير المبلغ سيؤدي إلى تعديل رصيد الخزنة.",
    confirm_deletion_title: "تأكيد الحذف", confirm_deletion_text: "لحذف هذا النشاط، اكتب الرمز أدناه.",
    delete_log: "حذف السجل", visible_to_managers: "مرئي للمدراء",
    hidden_from_managers: "مخفي عن المدراء", account_activity: "نشاط الحساب",
    operational_actions: "الإجراءات التشغيلية", recent_history: "السجل الحديث",
    my_account_activity: "نشاط حسابي", actions_performed: "الإجراءات المنفذة",
    no_records_section: "لا توجد سجلات في هذا القسم.", log_details: "تفاصيل السجل",
    click_to_hide: "مرئي للمدراء (اضغط للإخفاء)", click_to_show: "مخفي عن المدراء (اضغط للإظهار)",
    no_accounts: "لا توجد حسابات.", deposited_by: "تم الإيداع بواسطة", recipient: "المستلم",
    expense_name: "اسم المصروف", select_user: "اختر المستخدم",

    // Admin & Reports AR
    member: "العضو (المستخدم)", all_members: "كل الأعضاء", all_types: "كل الأنواع",
    income_type: "دخل (إضافة مال)", spending_type: "مصاريف", fund_project_type: "تمويل مشروع",
    withdraw_project_type: "سحب من مشروع", transfer_type: "تحويلات (إعطاء)", export_pdf_btn: "تصدير PDF",
    user_header: "المستخدم", role_header: "الدور", actions_header: "الإجراءات", capabilities: "صلاحيات مفعلة",
    data_mgmt: "إدارة البيانات", role_label_display: "الدور (للعرض فقط)",
    visible_desc: "إذا تم التحديد، يمكن للمدراء رؤية هذا الحساب في التقارير والقوائم.",
    filter_by_tag: "تصفية حسب الوسم..."
  },
  ku: {
    welcome_back: "بەخێرهاتی", username_placeholder: "ناوی بەکارهێنەر", password_placeholder: "وشەی تێپەڕ", login: "چوونە ژوورەوە", logout: "چوونە دەرەوە",
    vault_balance: "باڵانسی خەزنە", vault_details: "زانیاری خەزنە", projects: "پڕۆژەکان", my_projects: "پڕۆژەکانم",
    active: "چالاککراو", spent: "سەرفکراو", completed: "تەواوبوو", spending: "مەسروفات", start_date: "بەرواری دەستپێکردن", end_date: "بەرواری تەواوبوون",
    filter: "فلتەر", activity_log: "مێژووی مامەڵەکان", my_activity: "چالاکیەکانم", member_accounts: "حساباتی کەسەکان",
    accounting_reports: "حساباتی گشتی", admin_panel: "بەشی کۆنترۆڵ", manage_users: "بەڕێوەبردنی هەژمارەکان",
    add_employee: "زیادکردنی کارمەند", export_data: "ڕاکێشانی داتا", import_data: "هێنانی داتا",
    add_money: "زیادکردنی پارە", withdraw: "ڕاکێشان", fund: "خستنەسەر", create_project: "دروستکردنی پڕۆژە", log_expense: "تۆمارکردنی مەسروفات",
    give_money: "پێدانی پارە", description: "ناوەڕۆک", amount: "بڕ", note: "تێبینی (ئارەزوومەندانە)",
    save_changes: "خەزنکردنی گۆڕانکاری", delete: "سڕینەوە", edit: "گۆڕانکاری", confirm: "دڵنیابوونەوە", cancel: "پاشگەزبوونەوە",
    total_income: "کۆی هاتوو", total_expenses: "کۆی خەرجی", net_profit: "قازانجی پوخت",
    house: "ماڵەوە", general: "گشتی", project: "پڕۆژە", users: "بەکارهێنەران",
    type: "جۆر", tag: "تاگ", search: "گەڕان...",
    dashboard: "داشبۆرد", insufficient_funds: "پارەی پێویست نییە لە خەزنە",
    permissions: "دەسەڵاتەکان", edit_user: "دەستکاری بەکارهێنەر", create_user: "دروستکردنی بەکارهێنەر",

    // New Translations KU
    liquid_cash: "پارەی کاش (خەزنە)", total_assets: "کۆی گشتی سامان", allocated_funds: "پارەی تەرخانکراو",
    locked_in: "تەرخانکراوە لە", asset_allocation: "دابەشکردنی سامان", active_projects_breakdown: "وردەکاری پڕۆژە چالاکەکان",
    no_active_projects: "هیچ پڕۆژەیەک چالاک نییە.", access_denied: "ڕێگەپێدراو نییە",
    goal: "ئامانج", current_balance: "باڵانسی ئێستا", reactivate: "کاراکردنەوە", funded: "تەواوکراوە",
    project_activity: "چالاکی پڕۆژە", no_activity: "هیچ چالاکییەک نییە", remaining_goal_space: "بڕی ماوە بۆ ئامانج",
    confirm_completion: "دڵنیابوونەوە لە تەواوکردن", confirm_completion_text: "دڵنیایت لە سەرفکردنی ئەم بڕە پارەیەی کە ماوە",
    and_close_project: "و داخستنی ئەم پڕۆژەیە؟", yes_complete: "بەڵێ، تەواوکردن",
    confirm_reactivation: "دڵنیابوونەوە لە کاراکردنەوە", confirm_reactivation_text: "دڵنیایت لە کاراکردنەوەی ئەم پڕۆژەیە؟",
    restore_funds_note: "پارە سەرفکراوەکە دەگەڕێتەوە بۆ باڵانسی پڕۆژە.", yes_reactivate: "بەڵێ، کاراکردنەوە",
    edit_project: "دەستکاری پڕۆژە", project_name: "ناوی پڕۆژە", funding_goal: "ئامانجی پڕۆژە",
    security_check: "پشکنینی ئاسایش", delete_project_title: "سڕینەوەی پڕۆژە؟",
    delete_project_text: "پارەکە دەگەڕێتەوە بۆ خەزنە. کۆدەکە بنووسە بۆ دڵنیابوونەوە.",
    enter_security_code: "کۆدی ئاسایش بنووسە", type_code: "کۆدە ٣ ژمارەییەکە بنووسە",
    delete_project_btn: "سڕینەوەی پڕۆژە", no_projects_found: "هیچ پڕۆژەیەک نەدۆزرایەوە.",
    all: "هەموو", user: "بەکارهێنەر", no_records: "هیچ تۆمارێک نەدۆزرایەوە.",
    general_view: "گشتی", personal_view: "تایبەت", editing: "دەستکاریکردن",
    warning_edit: "ئاگاداری: گۆڕینی بڕی پارە کاریگەری دەبێت لەسەر باڵانسی خەزنە.",
    confirm_deletion_title: "دڵنیابوونەوە لە سڕینەوە", confirm_deletion_text: "بۆ سڕینەوەی ئەم چالاکییە، کۆدەکەی خوارەوە بنووسە.",
    delete_log: "سڕینەوەی تۆمار", visible_to_managers: "دەبینرێت بۆ بەڕێوەبەران",
    hidden_from_managers: "شاراوەیە لە بەڕێوەبەران", account_activity: "چالاکی هەژمار",
    operational_actions: "کارە ئیدارییەکان", recent_history: "مێژووی کۆتایی",
    my_account_activity: "چالاکی هەژمارەکەم", actions_performed: "کارە ئەنجامدراوەکان",
    no_records_section: "هیچ تۆمارێک نییە لەم بەشە.", log_details: "وردەکاری تۆمار",
    click_to_hide: "دەبینرێت (کلیک بکە بۆ شاردنەوە)", click_to_show: "شاراوەیە (کلیک بکە بۆ پیشاندان)",
    no_accounts: "هیچ هەژمارێک نییە.", deposited_by: "زیادکراوە لەلایەن", recipient: "وەرگر",
    expense_name: "ناوی مەسروفات", select_user: "بەکارهێنەر هەڵبژێرە",

    // Admin & Reports KU
    member: "ئەندام (بەکارهێنەر)", all_members: "هەموو ئەندامەکان", all_types: "هەموو جۆرەکان",
    income_type: "هاتوو (زیادکردنی پارە)", spending_type: "مەسروفات", fund_project_type: "خستنەسەری پڕۆژە",
    withdraw_project_type: "ڕاکێشان لە پڕۆژە", transfer_type: "حەواڵەکان (پێدان)", export_pdf_btn: "ڕاکێشانی PDF",
    user_header: "بەکارهێنەر", role_header: "ڕۆڵ", actions_header: "کردارەکان", capabilities: "دەسەڵاتی کارا",
    data_mgmt: "بەڕێوەبردنی داتا", role_label_display: "ڕۆڵ (تەنها بۆ پیشاندان)",
    visible_desc: "ئەگەر دیاری بکرێت، بەڕێوەبەران دەتوانن ئەم هەژمارە ببینن لە ڕاپۆرتەکان.",
    filter_by_tag: "فلتەر بەپێی تاگ..."
  }
};